Repository statisticsnorway/dapla-toolbelt-metadata, pull requests merged in 2025-05, with the labels that each got.

#225 Reorganized logic
  src/dapla_metadata/datasets/core.py
Labels: refactoring

#227 Only consider primary placement when mapping from a specific statistic to a subject field
  src/dapla_metadata/datasets/statistic_subject_mapping.py
  tests/datasets/resources/statistical_subject_structure/extract_secondary_subject.xml
  tests/datasets/test_statistic_subject_mapping.py
Labels: enhancement

#226 Support validation of required fields on existing metadata document
  .vscode/settings.json
  poetry.lock
  pyproject.toml
  src/dapla_metadata/__init__.py
  src/dapla_metadata/datasets/core.py
  src/dapla_metadata/datasets/dapla_dataset_path_info.py
  src/dapla_metadata/datasets/dataset_parser.py
  src/dapla_metadata/datasets/utility/constants.py
  src/dapla_metadata/datasets/utility/utils.py
  tests/datasets/constants.py
  tests/datasets/resources/existing_metadata_file/person_testdata_p2020-12-31_p2020-12-31_v1__DOC.json
  tests/datasets/test_dapla_dataset_path_info.py
  tests/datasets/test_datadoc_metadata.py
  tests/datasets/test_dataset_parser.py
  tests/datasets/test_validators.py
Labels: enhancement

#230 Release v0.7.0
  pyproject.toml
Labels: skip-changelog
